# .github/workflows/docker_image_ci.yml

name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # NEW STEP: Convert the repository name to lowercase for the Docker tag.
      - name: Convert repository name to lowercase
        id: string
        run: echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # UPDATED STEP: This now uses the lowercase repository name.
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./translateserver
          push: true
          # Use the 'env.REPO_LOWER' variable we created in the previous step.
          tags: |
            ghcr.io/${{ env.REPO_LOWER }}/translateserver:latest
            ghcr.io/${{ env.REPO_LOWER }}/translateserver:${{ github.sha }}
