# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2.20.0
        with:
          channel: 'stable'
          # Use flutter-version-file to read the version from pubspec.yaml
          # Path should be relative to the root of the repository.
          flutter-version-file: translateui/pubspec.yaml
      # check flutter version
      - name: Verify Flutter Version
        run: flutter --version
      # install dep 
      - name: Install dependencies
        run: flutter pub get
        working-directory: translateui/
      # analyze project
      - name: Analyze project source
        run: flutter analyze
        working-directory: translateui/
      # run tests 
      - name: Run tests
        run: flutter test
        working-directory: translateui/



